package ssn.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2015-12-14T19:28:11.350+01:00
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebService(targetNamespace = "http://ws.ssn/", name = "SSNWS")
@XmlSeeAlso({ObjectFactory.class})
public interface SSNWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteReservation", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteReservation")
    @WebMethod
    @ResponseWrapper(localName = "deleteReservationResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteReservationResponse")
    public ssn.ws.Result deleteReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createSport", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateSport")
    @WebMethod
    @ResponseWrapper(localName = "createSportResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateSportResponse")
    public ssn.ws.Result createSport(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Sport arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByEvent", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetUsersByEvent")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByEventResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetUsersByEventResponse")
    public ssn.ws.Result getUsersByEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteFieldSport", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteFieldSport")
    @WebMethod
    @ResponseWrapper(localName = "deleteFieldSportResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteFieldSportResponse")
    public ssn.ws.Result deleteFieldSport(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createManagerEntity", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateManagerEntity")
    @WebMethod
    @ResponseWrapper(localName = "createManagerEntityResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateManagerEntityResponse")
    public ssn.ws.Result createManagerEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.ManagerEntity arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://ws.ssn/", className = "ssn.ws.RegisterUser")
    @WebMethod
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.RegisterUserResponse")
    public ssn.ws.Result registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEventById", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventById")
    @WebMethod
    @ResponseWrapper(localName = "getEventByIdResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventByIdResponse")
    public ssn.ws.Result getEventById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "joinEvent", targetNamespace = "http://ws.ssn/", className = "ssn.ws.JoinEvent")
    @WebMethod
    @ResponseWrapper(localName = "joinEventResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.JoinEventResponse")
    public ssn.ws.Result joinEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEventsByFilters", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsByFilters")
    @WebMethod
    @ResponseWrapper(localName = "getEventsByFiltersResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsByFiltersResponse")
    public ssn.ws.Result getEventsByFilters(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getManagerEntities", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntities")
    @WebMethod
    @ResponseWrapper(localName = "getManagerEntitiesResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesResponse")
    public ssn.ws.Result getManagerEntities();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFieldById", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetFieldById")
    @WebMethod
    @ResponseWrapper(localName = "getFieldByIdResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetFieldByIdResponse")
    public ssn.ws.Result getFieldById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addField", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddField")
    @WebMethod
    @ResponseWrapper(localName = "addFieldResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddFieldResponse")
    public ssn.ws.Result addField(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Field arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "reportUser", targetNamespace = "http://ws.ssn/", className = "ssn.ws.ReportUser")
    @WebMethod
    @ResponseWrapper(localName = "reportUserResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.ReportUserResponse")
    public ssn.ws.Result reportUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Report arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getManagerEntitiesByEvent", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesByEvent")
    @WebMethod
    @ResponseWrapper(localName = "getManagerEntitiesByEventResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesByEventResponse")
    public ssn.ws.Result getManagerEntitiesByEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateField", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateField")
    @WebMethod
    @ResponseWrapper(localName = "updateFieldResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateFieldResponse")
    public ssn.ws.Result updateField(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Field arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReportTypes", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetReportTypes")
    @WebMethod
    @ResponseWrapper(localName = "getReportTypesResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetReportTypesResponse")
    public ssn.ws.Result getReportTypes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "leaveEvent", targetNamespace = "http://ws.ssn/", className = "ssn.ws.LeaveEvent")
    @WebMethod
    @ResponseWrapper(localName = "leaveEventResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.LeaveEventResponse")
    public ssn.ws.Result leaveEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getManagerEntitiesBySport", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesBySport")
    @WebMethod
    @ResponseWrapper(localName = "getManagerEntitiesBySportResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesBySportResponse")
    public ssn.ws.Result getManagerEntitiesBySport(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEventsByUser", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getEventsByUserResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsByUserResponse")
    public ssn.ws.Result getEventsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateManagerEntity", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateManagerEntity")
    @WebMethod
    @ResponseWrapper(localName = "updateManagerEntityResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateManagerEntityResponse")
    public ssn.ws.Result updateManagerEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.ManagerEntity arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEvents", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEvents")
    @WebMethod
    @ResponseWrapper(localName = "getEventsResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsResponse")
    public ssn.ws.Result getEvents();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSportById", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetSportById")
    @WebMethod
    @ResponseWrapper(localName = "getSportByIdResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetSportByIdResponse")
    public ssn.ws.Result getSportById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFieldsByManagerEntity", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetFieldsByManagerEntity")
    @WebMethod
    @ResponseWrapper(localName = "getFieldsByManagerEntityResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetFieldsByManagerEntityResponse")
    public ssn.ws.Result getFieldsByManagerEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReservationsByField", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetReservationsByField")
    @WebMethod
    @ResponseWrapper(localName = "getReservationsByFieldResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetReservationsByFieldResponse")
    public ssn.ws.Result getReservationsByField(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetUserDetailsResponse")
    public ssn.ws.Result getUserDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateFieldSport", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateFieldSport")
    @WebMethod
    @ResponseWrapper(localName = "updateFieldSportResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateFieldSportResponse")
    public ssn.ws.Result updateFieldSport(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteReservations", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteReservations")
    @WebMethod
    @ResponseWrapper(localName = "deleteReservationsResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteReservationsResponse")
    public ssn.ws.Result deleteReservations(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ssn.ws.Reservation> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteField", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteField")
    @WebMethod
    @ResponseWrapper(localName = "deleteFieldResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteFieldResponse")
    public ssn.ws.Result deleteField(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEventsHistoryByUser", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsHistoryByUser")
    @WebMethod
    @ResponseWrapper(localName = "getEventsHistoryByUserResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetEventsHistoryByUserResponse")
    public ssn.ws.Result getEventsHistoryByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addReservation", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddReservation")
    @WebMethod
    @ResponseWrapper(localName = "addReservationResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddReservationResponse")
    public ssn.ws.Result addReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Reservation arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createEvent", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateEvent")
    @WebMethod
    @ResponseWrapper(localName = "createEventResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateEventResponse")
    public ssn.ws.Result createEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.Event arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createReportType", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateReportType")
    @WebMethod
    @ResponseWrapper(localName = "createReportTypeResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.CreateReportTypeResponse")
    public ssn.ws.Result createReportType(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.ReportType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSports", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetSports")
    @WebMethod
    @ResponseWrapper(localName = "getSportsResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetSportsResponse")
    public ssn.ws.Result getSports();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addFieldSport", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddFieldSport")
    @WebMethod
    @ResponseWrapper(localName = "addFieldSportResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddFieldSportResponse")
    public ssn.ws.Result addFieldSport(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteManagerEntity", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteManagerEntity")
    @WebMethod
    @ResponseWrapper(localName = "deleteManagerEntityResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.DeleteManagerEntityResponse")
    public ssn.ws.Result deleteManagerEntity(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getManagerEntitiesById", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesById")
    @WebMethod
    @ResponseWrapper(localName = "getManagerEntitiesByIdResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.GetManagerEntitiesByIdResponse")
    public ssn.ws.Result getManagerEntitiesById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addReservations", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddReservations")
    @WebMethod
    @ResponseWrapper(localName = "addReservationsResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.AddReservationsResponse")
    public ssn.ws.Result addReservations(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ssn.ws.Reservation> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateUser")
    @WebMethod
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.ssn/", className = "ssn.ws.UpdateUserResponse")
    public ssn.ws.Result updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ssn.ws.User arg0
    );
}
